In [8]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

# File to Load (Remember to Change These)
school_data_to_load = Path("Resources/schools_complete.csv")
student_data_to_load = Path("Resources/students_complete.csv")

# Read School and Student Data File and store into Pandas DataFrames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset.  
school_data_complete = pd.merge(student_data, school_data, how="left", on=["school_name", "school_name"])
school_data_complete.head(20)

,Student ID,student_name,gender,grade,school_name,reading_score,math_score,School ID,type,size,budget
0,0,Paul Bradley,M,9th,Huang High School,66,79,0,District,2917,1910635
1,1,Victor Smith,M,12th,Huang High School,94,61,0,District,2917,1910635
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60,0,District,2917,1910635
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58,0,District,2917,1910635
4,4,Bonnie Ray,F,9th,Huang High School,97,84,0,District,2917,1910635
5,5,Bryan Miranda,M,9th,Huang High School,94,94,0,District,2917,1910635
6,6,Sheena Carter,F,11th,Huang High School,82,80,0,District,2917,1910635
7,7,Nicole Baker,F,12th,Huang High School,96,69,0,District,2917,1910635
8,8,Michael Roth,M,10th,Huang High School,95,87,0,District,2917,1910635
9,9,Matthew Greene,M,10th,Huang High School,96,84,0,District,2917,1910635
10,10,Andrew Alexander,M,10th,Huang High School,90,70,0,District,2917,1910635
11,11,Daniel Cooper,M,10th,Huang High School,78,77,0,District,2917,1910635
12,12,Brittney Walker,F,9th,Huang High School,64,79,0,District,2917,1910635
13,13,William Long,M,9th,Huang High School,71,79,0,District,2917,1910635
14,14,Tammy Hebert,F,10th,Huang High School,85,67,0,District,2917,1910635
15,15,Dr. Jordan Carson,M,11th,Huang High School,94,88,0,District,2917,1910635
16,16,Donald Zamora,M,9th,Huang High School,88,55,0,District,2917,1910635
17,17,Kimberly Santiago,F,9th,Huang High School,74,75,0,District,2917,1910635
18,18,Kevin Stevens,M,9th,Huang High School,64,69,0,District,2917,1910635
19,19,Brandi Lyons,F,9th,Huang High School,89,80,0,District,2917,1910635

In [9]:
students_passing_math=(school_data_complete["math_score"] >= 70).sum()
students_passing_math

29370

In [10]:
#huang_df = school_data_complete.groupby[["school_name"]=="Huang High School"]
#Huang = school_data_complete.groupby("school_name").get_group("Huang High School")
#P=Huang(["math_score"]>70).count.sum()
#Print(Huang["reading_score"].mean())

In [11]:
#students passing math
school_names = ["Huang High School", "Figueroa High School", "Shelton High School", "Hernandez High School",
                "Wilson High School", "Cabrera High School", "Bailey High School", "Holden High School",
                "Pena High School", "Wright High School", "Rodriguez High School", "Johnson High School",
                "Ford High School", "Thomas High School"]

# Create an empty list to store the number of students passing math for each school
school_students_pass_math = []

# Loop through each school and calculate the number of students passing math
for school_name in school_names:
    school_df = school_data_complete[school_data_complete["school_name"] == school_name]
    students_passing_math = (school_df["math_score"] >= 70).sum()
    school_students_pass_math.append(students_passing_math)

# Create a DataFrame to store the results
school_students_pass_math_data = {'Students Passing Math': school_students_pass_math}
per_school_pass_math = pd.DataFrame(school_students_pass_math_data, index=None)

# Print the result
print(per_school_pass_math)

    Students Passing Math
0                    1916
1                    1946
2                    1653
3                    3094
4                    2143
5                    1749
6                    3318
7                     395
8                     910
9                    1680
10                   2654
11                   3145
12                   1871
13                   1525

In [12]:
school_list="none"
#[
#"Huang High School",
#"Figueroa High School",
#"Shelton High School",
#"Hernandez High School",
#"Griffin High School",
#"Wilson High School",
#"Cabrera High School",
#"Bailey High School",
#"Holden High School",
#"Pena High School",
#"Wright High School",
#"Rodriguez High School",
#"Johnson High School",
#"Ford High School",
#"Thomas High School"
#]
#print(school_list)

In [13]:
Huang_hs_df = school_data_complete[school_data_complete["school_name"] == "Huang High School"]
Figueroa_hs_df = school_data_complete[school_data_complete["school_name"] == "Figueroa High School"]
Shelton_hs_df = school_data_complete[school_data_complete["school_name"] == "Shelton High School"]
Hernandez_hs_df = school_data_complete[school_data_complete["school_name"] == "Hernandez High School"]
Griffin_hs_df = school_data_complete[school_data_complete["school_name"] == "Griffin High School"]
Wilson_hs_df = school_data_complete[school_data_complete["school_name"] == "Wilson High School"]
Cabrera_hs_df = school_data_complete[school_data_complete["school_name"] == "Cabrera High School"]
Bailey_hs_df = school_data_complete[school_data_complete["school_name"] == "Bailey High School"]
Holden_hs_df = school_data_complete[school_data_complete["school_name"] == "Holden High School"]
Pena_hs_df = school_data_complete[school_data_complete["school_name"] == "Pena High School"]
Wright_hs_df = school_data_complete[school_data_complete["school_name"] == "Wright High School"]
Rodriguez_hs_df = school_data_complete[school_data_complete["school_name"] == "Rodriguez High School"]
Johnson_hs_df = school_data_complete[school_data_complete["school_name"] == "Johnson High School"]
Ford_hs_df = school_data_complete[school_data_complete["school_name"] == "Ford High School"]
Thomas_hs_df = school_data_complete[school_data_complete["school_name"] == "Thomas High School"]

In [14]:
school_students_pass_math=[]
school_students_pass_math.append((Huang_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Figueroa_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Shelton_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Hernandez_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Wilson_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Cabrera_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Bailey_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Holden_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Pena_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Wright_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Rodriguez_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Johnson_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Ford_hs_df["math_score"] >= 70).sum())
school_students_pass_math.append((Thomas_hs_df["math_score"] >= 70).sum())
print(count_passing_math)

school_students_pass_math_data = {'Students Passing Math': school_students_pass_math}
per_school_pass_math = pd.DataFrame(school_students_pass_math_data, index=None)

per_school_pass_math

NameError: name 'count_passing_math' is not defined

In [ ]:
student_count=[]
student_count.append(Huang_hs_df["student_name"].count())
student_count.append(Figueroa_hs_df["student_name"].count())
student_count.append(Shelton_hs_df["student_name"].count())
student_count.append(Hernandez_hs_df["student_name"].count())
student_count.append(Griffin_hs_df["student_name"].count())
student_count.append(Wilson_hs_df["student_name"].count())
student_count.append(Cabrera_hs_df["student_name"].count())
student_count.append(Bailey_hs_df["student_name"].count())
student_count.append(Holden_hs_df["student_name"].count())
student_count.append(Pena_hs_df["student_name"].count())
student_count.append(Wright_hs_df["student_name"].count())
student_count.append(Rodriguez_hs_df["student_name"].count())
student_count.append(Johnson_hs_df["student_name"].count())
student_count.append(Ford_hs_df["student_name"].count())
student_count.append(Thomas_hs_df["student_name"].count())

student_count_data = {'Student Count Per School': student_count}

per_school_student_count = pd.DataFrame(student_count_data, index=None)

per_school_student_count.head(15)

In [ ]:
math_score_avg=[]
math_score_avg.append(Huang_hs_df["math_score"].mean())
math_score_avg.append(Figueroa_hs_df["math_score"].mean())
math_score_avg.append(Shelton_hs_df["math_score"].mean())
math_score_avg.append(Hernandez_hs_df["math_score"].mean())
math_score_avg.append(Griffin_hs_df["math_score"].mean())
math_score_avg.append(Wilson_hs_df["math_score"].mean())
math_score_avg.append(Cabrera_hs_df["math_score"].mean())
math_score_avg.append(Bailey_hs_df["math_score"].mean())
math_score_avg.append(Holden_hs_df["math_score"].mean())
math_score_avg.append(Pena_hs_df["math_score"].mean())
math_score_avg.append(Wright_hs_df["math_score"].mean())
math_score_avg.append(Rodriguez_hs_df["math_score"].mean())
math_score_avg.append(Johnson_hs_df["math_score"].mean())
math_score_avg.append(Ford_hs_df["math_score"].mean())
math_score_avg.append(Thomas_hs_df["math_score"].mean())

math_score_avg_data = {'Math Score Avg Per School': math_score_avg}
per_school_math = pd.DataFrame(math_score_avg_data, index=None)

per_school_math.head(15)

In [ ]:
reading_score_avg=[]
reading_score_avg.append(Huang_hs_df["reading_score"].mean())
reading_score_avg.append(Figueroa_hs_df["reading_score"].mean())
reading_score_avg.append(Shelton_hs_df["reading_score"].mean())
reading_score_avg.append(Hernandez_hs_df["reading_score"].mean())
reading_score_avg.append(Griffin_hs_df["reading_score"].mean())
reading_score_avg.append(Wilson_hs_df["reading_score"].mean())
reading_score_avg.append(Cabrera_hs_df["reading_score"].mean())
reading_score_avg.append(Bailey_hs_df["reading_score"].mean())
reading_score_avg.append(Holden_hs_df["reading_score"].mean())
reading_score_avg.append(Pena_hs_df["reading_score"].mean())
reading_score_avg.append(Wright_hs_df["reading_score"].mean())
reading_score_avg.append(Rodriguez_hs_df["reading_score"].mean())
reading_score_avg.append(Johnson_hs_df["reading_score"].mean())
reading_score_avg.append(Ford_hs_df["reading_score"].mean())
reading_score_avg.append(Thomas_hs_df["reading_score"].mean())

reading_score_avg_data = {'Reading Score Avg Per School': reading_score_avg}
per_school_reading = pd.DataFrame(reading_score_avg_data, index=None)


per_school_reading.sum

In [ ]:
budget=school_data.iloc[:,4]

In [ ]:
budget_per_capita=school_data.iloc[:,4]/school_data.iloc[:,3]
budget_per_capita

In [ ]:
students_passing_math_and_reading = school_data_complete[(school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)]
school_students_passing_math_and_reading = students_passing_math_and_reading.groupby(["school_name"]).size()

students_passing_math_and_reading.value_counts()

In [ ]:
Huang = school_data_complete.groupby[["school_name"]=="Huang High School"]
#Huang = school_data_complete.groupby("school_name").get_group("Huang High School")
P=Huang(["math_score"]>70).count.sum()
Print(Huang["reading_score"].mean())

In [ ]:
passing_math=(school_data_complete["math_score"] >= 70).sum
passing_math()

In [ ]:
passing_reading=(school_data_complete["reading_score"] >= 70).sum
passing_reading()

In [ ]:
# Use the provided code to calculate the number of students per school that passed both math and reading with scores of 70 or higher
students_passing_math_and_reading = school_data_complete[(school_data_complete["reading_score"] >= 70) & (school_data_complete["math_score"] >= 70)]
school_students_passing_math_and_reading = students_passing_math_and_reading.groupby(["school_name"]).size()

students_passing_math_and_reading.value_counts()

In [ ]:
Huang_hs_df = school_data_complete[school_data_complete["school_name"] == "Huang High School"]
Figueroa_hs_df = school_data_complete[school_data_complete["school_name"] == "Figueroa High School"]
Shelton_hs_df = school_data_complete[school_data_complete["school_name"] == "Shelton High School"]
Hernandez_hs_df = school_data_complete[school_data_complete["school_name"] == "Hernandez High School"]
Griffin_hs_df = school_data_complete[school_data_complete["school_name"] == "Griffin High School"]
Wilson_hs_df = school_data_complete[school_data_complete["school_name"] == "Wilson High School"]
Cabrera_hs_df = school_data_complete[school_data_complete["school_name"] == "Cabrera High School"]
Bailey_hs_df = school_data_complete[school_data_complete["school_name"] == "Bailey High School"]
Holden_hs_df = school_data_complete[school_data_complete["school_name"] == "Holden High School"]
Pena_hs_df = school_data_complete[school_data_complete["school_name"] == "Pena High School"]
Wright_hs_df = school_data_complete[school_data_complete["school_name"] == "Wright High School"]
Rodriguez_hs_df = school_data_complete[school_data_complete["school_name"] == "Rodriguez High School"]
Johnson_hs_df = school_data_complete[school_data_complete["school_name"] == "Johnson High School"]
Ford_hs_df = school_data_complete[school_data_complete["school_name"] == "Ford High School"]
Thomas_hs_df = school_data_complete[school_data_complete["school_name"] == "Thomas High School"]